env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
rules: {}
globals:
  - Hud
  - Road
  - AutopilotControls
  - AIForwardControls
  - Car
  - Sensor
  - NeuralNetwork
  - NNVisualizer
